---
meta:
  name: homebrew-cf
  target: pipes@main
  # url: https://pipes.scalecf.net team: main

  github:
    owner: cloudfoundry-community
    repo: homebrew-cf
    private_key: ((github.private-key))
    access_token: ((github.access-token))

  debian:
    s3_bucket: apt.community.cloudfoundry.org
    aws_access_key: ((aws-access-key))
    aws_secret_key: ((aws-secret-key))
    region: "us-west-2"

  gpg:
    id:  ((gpg-packaging-id))
    public_key:  ((gpg-packaging-public))
    private_key: ((gpg-packaging-private))

  pivnet:
    api-token: ((pivnet-token))
