---
meta:
  name: homebrew-recipes
  target: sw

  github:
    owner: starkandwayne
    repo: homebrew-cf
    private_key: (( vault  "secret/pipelines/shared/github:private_key" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  debian:
    s3_bucket: apt.starkandwayne.com
    aws_access_key: (( vault "secret/pipelines/homebrew/aws:aws_access_key" ))
    aws_secret_key: (( vault "secret/pipelines/homebrew/aws:aws_secret_key" ))

  gpg:
    id:  (( vault "secret/pipelines/homebrew/gpg:id" ))
    public_key:  (( vault "secret/pipelines/homebrew/gpg:public" ))
    private_key: (( vault "secret/pipelines/homebrew/gpg:private" ))

  pivnet:
    api-token: (( vault "secret/pipelines/" meta.pipeline "/pivnet:api-token" ))
