---
meta:
  name: homebrew-cf
  target: ohio-sw
  # url: https://ci2.starkandwayne.com team: starkandwayne

  github:
    owner: starkandwayne
    repo: homebrew-cf
    private_key: ((github-private-key))
    access_token: ((github-access-token))

  debian:
    s3_bucket: apt.starkandwayne.com
    aws_access_key: ((aws-secret-key))
    aws_secret_key: ((aws-access-key))

  gpg:
    id:  ((gpg-packaging-id))
    public_key:  ((gpg-packaging-public))
    private_key: ((gpg-packaging-private))

  pivnet:
    api-token: ((pivnet-token))
